/** Read-only, bounded Java source loading for first-party native analyzers. */

import { constants, type BigIntStats } from "node:fs";
import { lstat, open, readdir, type FileHandle } from "node:fs/promises";
import { basename, dirname, extname, join, parse, relative, resolve } from "node:path";

export const JAVA_MAX_SOURCE_BYTES = 2 * 1024 * 1024;
export const JAVA_MAX_SOURCE_FILES = 10_000;
export const JAVA_MAX_TOTAL_BYTES = 64 * 1024 * 1024;
export const JAVA_MAX_DEPTH = 32;
export const JAVA_MAX_DISCOVERY_ENTRIES = 50_000;

const MAX_LIMITATIONS = 24;
const IGNORED_DIRS = new Set([
  ".cache", ".git", ".gradle", ".hg", ".idea", ".mvn", ".svn", ".vscode",
  "bin", "build", "coverage", "dist", "generated", "node_modules", "out", "target", "vendor",
]);
const NON_PRODUCTION_DIRS = new Set([
  "demo", "demos", "example", "examples", "fixture", "fixtures", "generated-test-sources",
  "integration-test", "integration-tests", "sample", "samples", "src/test", "test", "testdata", "tests",
]);

export interface JavaDocument {
  path: string;
  content: string;
}

export interface JavaProject {
  target: string;
  root: string;
  files: JavaDocument[];
  limitations?: string[];
}

export type JavaProjectInput = string | JavaProject | Promise<JavaProject>;

function sourcePath(path: string): boolean {
  return extname(path).toLowerCase() === ".java";
}

function nonProductionSourceName(name: string): boolean {
  const lower = name.toLowerCase();
  return lower.startsWith("test") || lower.endsWith("test.java") || lower.endsWith("tests.java") ||
    lower.endsWith("it.java");
}

function generatedSource(name: string, content: string): boolean {
  const lower = name.toLowerCase();
  if (lower.endsWith("generated.java") || lower.endsWith("_gen.java")) return true;
  const header = content.split(/\r?\n/, 10).join("\n");
  return /(?:generated|autogenerated).{0,100}(?:do not edit|do not modify)/is.test(header) ||
    /(?:do not edit|do not modify).{0,100}(?:generated|autogenerated)/is.test(header);
}

function collector(): { add: (value: string) => void; finish: () => string[] } {
  const values = new Set<string>();
  let omitted = 0;
  return {
    add(value) {
      if (values.size < MAX_LIMITATIONS - 1) values.add(value);
      else omitted++;
    },
    finish() {
      return [
        ...values,
        ...(omitted ? [`${omitted} additional Java source limitations omitted.`] : []),
      ].sort();
    },
  };
}

function normalized(path: string): string {
  return path.replace(/\\/g, "/");
}

function sameIdentity(left: BigIntStats, right: BigIntStats): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}

function unchangedFile(before: BigIntStats, after: BigIntStats): boolean {
  return sameIdentity(before, after) && before.size === after.size &&
    before.mtimeNs === after.mtimeNs && before.ctimeNs === after.ctimeNs;
}

async function hasSymbolicLinkAncestor(absoluteTarget: string): Promise<boolean> {
  const filesystemRoot = parse(absoluteTarget).root;
  const ancestors: string[] = [];
  let current = dirname(absoluteTarget);
  while (current !== filesystemRoot) {
    ancestors.push(current);
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }
  for (const ancestor of ancestors.reverse()) {
    const metadata = await lstat(ancestor).catch(() => undefined);
    if (!metadata) break;
    if (metadata.isSymbolicLink()) return true;
  }
  return false;
}

async function readJavaFile(
  absolute: string,
  displayPath: string,
  remainingBytes: number,
): Promise<{ document?: JavaDocument; bytes?: number; limitation?: string; totalExceeded?: boolean }> {
  let handle: FileHandle | undefined;
  try {
    const before = await lstat(absolute, { bigint: true });
    if (before.isSymbolicLink()) return { limitation: `Skipped symbolic-link Java source ${displayPath}.` };
    if (!before.isFile()) return {};
    if (before.size > BigInt(JAVA_MAX_SOURCE_BYTES)) {
      return { limitation: `Skipped oversized Java source ${displayPath} (limit: ${JAVA_MAX_SOURCE_BYTES} bytes).` };
    }
    if (before.size > BigInt(remainingBytes)) return { bytes: Number(before.size), totalExceeded: true };

    const noFollow = typeof constants.O_NOFOLLOW === "number" ? constants.O_NOFOLLOW : 0;
    handle = await open(absolute, constants.O_RDONLY | noFollow);
    const opened = await handle.stat({ bigint: true });
    if (!opened.isFile() || !sameIdentity(before, opened)) {
      return { limitation: `Skipped changed Java source ${displayPath}.` };
    }
    if (opened.size > BigInt(JAVA_MAX_SOURCE_BYTES)) {
      return { limitation: `Skipped oversized Java source ${displayPath} (limit: ${JAVA_MAX_SOURCE_BYTES} bytes).` };
    }
    if (opened.size > BigInt(remainingBytes)) return { bytes: Number(opened.size), totalExceeded: true };
    const size = Number(opened.size);
    const bytes = Buffer.alloc(size);
    let offset = 0;
    while (offset < size) {
      const { bytesRead } = await handle.read(bytes, offset, size - offset, offset);
      if (bytesRead === 0) return { limitation: `Skipped changed Java source ${displayPath}.` };
      offset += bytesRead;
    }
    if (!unchangedFile(opened, await handle.stat({ bigint: true }))) {
      return { bytes: size, limitation: `Skipped changed Java source ${displayPath}.` };
    }
    let content: string;
    try {
      content = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    } catch {
      return { bytes: size, limitation: `Skipped non-UTF-8 Java source ${displayPath}.` };
    }
    if (generatedSource(basename(absolute), content)) return { bytes: size };
    return { document: { path: normalized(displayPath), content }, bytes: size };
  } catch {
    return { limitation: `Skipped unreadable Java source ${displayPath}.` };
  } finally {
    await handle?.close().catch(() => undefined);
  }
}

async function loadUncached(target: string): Promise<JavaProject> {
  const absoluteTarget = resolve(target);
  const limitations = collector();
  if (await hasSymbolicLinkAncestor(absoluteTarget)) {
    return {
      target: absoluteTarget,
      root: sourcePath(absoluteTarget) ? dirname(absoluteTarget) : absoluteTarget,
      files: [],
      limitations: [
        "Skipped Java source target because a symbolic-link ancestor would be followed; symbolic-link ancestors are never allowed.",
      ],
    };
  }
  const metadata = await lstat(absoluteTarget).catch(() => undefined);
  if (!metadata) {
    return { target: absoluteTarget, root: absoluteTarget, files: [], limitations: ["Java source target was unreadable."] };
  }
  if (metadata.isSymbolicLink()) {
    return {
      target: absoluteTarget,
      root: dirname(absoluteTarget),
      files: [],
      limitations: ["Skipped symbolic-link Java source target; symbolic links are never followed."],
    };
  }
  if (metadata.isFile()) {
    if (!sourcePath(absoluteTarget)) return { target: absoluteTarget, root: dirname(absoluteTarget), files: [] };
    const loaded = await readJavaFile(absoluteTarget, basename(absoluteTarget), JAVA_MAX_TOTAL_BYTES);
    if (loaded.limitation) limitations.add(loaded.limitation);
    return {
      target: absoluteTarget,
      root: dirname(absoluteTarget),
      files: loaded.document ? [loaded.document] : [],
      limitations: limitations.finish(),
    };
  }
  if (!metadata.isDirectory()) return { target: absoluteTarget, root: absoluteTarget, files: [] };

  const files: JavaDocument[] = [];
  let entriesInspected = 0;
  let totalBytes = 0;
  let stopped = false;

  async function walk(directory: string, depth: number): Promise<void> {
    if (stopped) return;
    if (depth > JAVA_MAX_DEPTH) {
      limitations.add(`Skipped Java source below ${normalized(relative(absoluteTarget, directory)) || "."} beyond the ${JAVA_MAX_DEPTH}-level depth bound.`);
      return;
    }
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => undefined);
    if (!entries) {
      limitations.add(`Skipped unreadable Java source directory ${normalized(relative(absoluteTarget, directory)) || "."}.`);
      return;
    }
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      if (stopped) break;
      entriesInspected++;
      if (entriesInspected > JAVA_MAX_DISCOVERY_ENTRIES) {
        limitations.add(`Stopped Java source discovery at the ${JAVA_MAX_DISCOVERY_ENTRIES}-entry bound.`);
        stopped = true;
        break;
      }
      const absolute = join(directory, entry.name);
      const display = normalized(relative(absoluteTarget, absolute));
      if (entry.isSymbolicLink()) {
        limitations.add(`Skipped symbolic-link Java source entry ${display}.`);
        continue;
      }
      if (entry.isDirectory()) {
        const lower = entry.name.toLowerCase();
        const relativeDirectory = display.toLowerCase();
        const productionPackage = relativeDirectory.startsWith("src/main/java/");
        if (
          IGNORED_DIRS.has(lower) || NON_PRODUCTION_DIRS.has(relativeDirectory) ||
          (!productionPackage && NON_PRODUCTION_DIRS.has(lower))
        ) continue;
        await walk(absolute, depth + 1);
        continue;
      }
      if (!entry.isFile() || !sourcePath(entry.name) || nonProductionSourceName(entry.name)) continue;
      if (files.length >= JAVA_MAX_SOURCE_FILES) {
        limitations.add(`Stopped Java source discovery at the ${JAVA_MAX_SOURCE_FILES}-file bound.`);
        stopped = true;
        break;
      }
      const loaded = await readJavaFile(absolute, display, JAVA_MAX_TOTAL_BYTES - totalBytes);
      if (loaded.limitation) limitations.add(loaded.limitation);
      if (loaded.totalExceeded) {
        limitations.add(`Stopped Java source discovery at the ${JAVA_MAX_TOTAL_BYTES}-byte project bound.`);
        stopped = true;
        break;
      }
      totalBytes += loaded.bytes ?? 0;
      if (loaded.document) files.push(loaded.document);
    }
  }

  await walk(absoluteTarget, 0);
  return { target: absoluteTarget, root: absoluteTarget, files, limitations: limitations.finish() };
}

export function resolveJavaProject(input: JavaProjectInput): Promise<JavaProject> {
  return typeof input === "string" ? loadUncached(input) : Promise.resolve(input);
}

export function createCachedJavaProjectLoader(target: string): () => Promise<JavaProject> {
  let cached: Promise<JavaProject> | undefined;
  return () => cached ??= loadUncached(target);
}
