import { chmod, lstat, mkdir, mkdtemp, readdir, readFile, rename, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { Ajv } from "ajv";
import { scanRepositoryTrust } from "./index.js";
import {
  applyRepositoryCleanup,
  planRepositoryCleanup,
  resetCleanupRuntimeStateForTests,
  rollbackRepositoryCleanup,
  sanitizeAsset,
} from "./cleanup.js";

const cleanup: string[] = [];

async function fixture(): Promise<{ root: string; store: string }> {
  const root = await mkdtemp(join(tmpdir(), "codeinspectus-v33-cleanup-"));
  const store = await mkdtemp(join(tmpdir(), "codeinspectus-v33-store-"));
  cleanup.push(root, store);
  return { root, store };
}

afterEach(async () => {
  resetCleanupRuntimeStateForTests();
  await Promise.all(cleanup.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

const PNG_WITH_AI_METADATA = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAFHRFWHRTb2Z0d2FyZQBDbGF1ZGUgQ29kZUU+WAAAAAAASUVORK5CYII=",
  "base64",
);

function idsFor(document: Awaited<ReturnType<typeof scanRepositoryTrust>>, file: string): string[] {
  return document.artifacts.filter((artifact) => artifact.location.file === file && artifact.remediation.eligible)
    .map((artifact) => artifact.artifact_id);
}

describe("V3.3 verified repository cleanup", () => {
  test("plans exact source edits, applies them with a managed checkpoint, rescans, and rolls back", async () => {
    const { root, store } = await fixture();
    const source = join(root, "app.ts");
    const original = "// Generated by Claude Code\nconst user\u200Bname = 'safe';\n";
    await writeFile(source, original, "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "app.ts");
    expect(artifactIds).toHaveLength(2);

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(plan).toMatchObject({ outcome: "ready", checkpoint: { strategy: "managed_content_backup" } });
    expect(plan.operations).toEqual([
      expect.objectContaining({ action: "edit_text", mode: "in_place", artifact_ids: expect.arrayContaining(artifactIds) }),
    ]);
    const planJsonSchema = JSON.parse(await readFile("schemas/codeinspectus-cleanup-plan-1.0.0.schema.json", "utf8"));
    const planValidator = new Ajv({ strict: false, validateSchema: false }).compile(planJsonSchema);
    expect(planValidator(plan), JSON.stringify(planValidator.errors)).toBe(true);

    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
    }, { storeRoot: store })).rejects.toThrow(/rights_to_modify/i);

    const applied = await applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
      confirm_rights_to_modify: true,
    }, { storeRoot: store });
    expect(applied).toMatchObject({
      outcome: "incomplete",
      checkpoint: { state: "created", managed: true, content_retained: true },
      verification: {
        same_validators_ran: true,
        targeted_artifacts_resolved: true,
        repository_checks: { state: "not_run", required: true },
      },
    });
    expect(await readFile(source, "utf8")).toBe("const username = 'safe';\n");
    const audit = await readFile(applied.audit_log_path, "utf8");
    expect(audit).not.toContain(original);
    expect(audit).toContain(artifactIds[0]!);
    const trustJsonSchema = JSON.parse(await readFile("schemas/codeinspectus-repository-trust-1.0.0.schema.json", "utf8"));
    const resultJsonSchema = JSON.parse(await readFile("schemas/codeinspectus-cleanup-result-1.0.0.schema.json", "utf8"));
    const resultAjv = new Ajv({ strict: false, validateSchema: false });
    resultAjv.addSchema(trustJsonSchema);
    const resultValidator = resultAjv.compile(resultJsonSchema);
    expect(resultValidator(applied), JSON.stringify(resultValidator.errors)).toBe(true);

    resetCleanupRuntimeStateForTests();
    const rolledBack = await rollbackRepositoryCleanup({ cleanup_id: applied.cleanup_id, confirm_rollback: true }, { storeRoot: store });
    expect(rolledBack.outcome).toBe("rolled_back");
    expect(rolledBack.verification.same_validators_ran).toBe(true);
    expect(rolledBack.audit_log_path).toBe(join(store, applied.cleanup_id, "rollback.json"));
    expect(await readFile(rolledBack.audit_log_path, "utf8")).not.toContain(original);
    expect(await readFile(source, "utf8")).toBe(original);
  });

  test("fails closed when approval scope or the planned preimage changes", async () => {
    const { root, store } = await fixture();
    const source = join(root, "app.ts");
    await writeFile(source, "const user\u200Bname = true;\n", "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });

    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: [],
      confirm_cleanup: true,
    }, { storeRoot: store })).rejects.toThrow(/exactly match/i);

    await writeFile(source, "const user\u200Bname = false;\n", "utf8");
    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
    }, { storeRoot: store })).rejects.toThrow(/preimage|changed/i);
    expect(await readFile(source, "utf8")).toContain("false");
  });

  test("does not delete code that follows a block-comment attribution on the same line", async () => {
    const { root } = await fixture();
    await writeFile(join(root, "app.ts"), "/* Generated by Claude Code */ const retained = true;\n", "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "app.ts");
    expect(artifactIds).toHaveLength(1);

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(plan.outcome).toBe("blocked");
    expect(plan.blockers[0]?.reason).toMatch(/standalone attribution comments/i);
  });

  test.each([
    ["one.ts", "/* Generated by Claude Code */ export const retained = 1; /* keep */\n"],
    ["page.html", "<!-- Generated by Claude --><div id=\"kept\"></div><!-- end -->\n"],
    ["cr.py", "# Generated by Claude Code\rprint('kept')\r"],
  ])("blocks attribution-line removal when %s has code on the same scanned line", async (file, content) => {
    const { root } = await fixture();
    await writeFile(join(root, file), content, "utf8");
    const artifactIds = idsFor(await scanRepositoryTrust(root), file);
    expect(artifactIds).toHaveLength(1);

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });

    expect(plan.outcome).toBe("blocked");
    expect(plan.blockers[0]?.reason).toMatch(/standalone attribution comments/i);
  });

  test("removes a standalone HTML attribution comment line and keeps CRLF neighbours intact", async () => {
    const { root, store } = await fixture();
    const page = join(root, "page.html");
    await writeFile(page, "<!doctype html>\r\n<!-- Generated by Claude Code -->\r\n<p>kept</p>\r\n", "utf8");
    const artifactIds = idsFor(await scanRepositoryTrust(root), "page.html");

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(plan.outcome).toBe("ready");
    await applyRepositoryCleanup({
      plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true, confirm_rights_to_modify: true,
    }, { storeRoot: store });

    expect(await readFile(page, "utf8")).toBe("<!doctype html>\r\n<p>kept</p>\r\n");
  });

  test("removes only the verified marker from a file that starts with a UTF-8 BOM", async () => {
    const { root, store } = await fixture();
    const source = join(root, "bom.ts");
    await writeFile(source, "﻿const user​name = 1;\n", "utf8");
    const artifactIds = idsFor(await scanRepositoryTrust(root), "bom.ts");
    expect(artifactIds).toHaveLength(1);

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(plan.outcome).toBe("ready");
    await applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true }, { storeRoot: store });

    expect(await readFile(source, "utf8")).toBe("﻿const username = 1;\n");
  });

  test("blocks a source-integrity edit when the bytes at the offset are not the recorded code points", async () => {
    const { root } = await fixture();
    await writeFile(join(root, "app.ts"), "const user​name = 1;\n", "utf8");
    const shiftedOffsetScan = async (target: string) => {
      const document = await scanRepositoryTrust(target);
      return {
        ...document,
        artifacts: document.artifacts.map((artifact) => ({
          ...artifact,
          evidence: {
            ...artifact.evidence,
            attributes: artifact.evidence.attributes.map((item) => item.name === "utf8_byte_offset" ? { ...item, value: 9 } : item),
          },
        })),
      };
    };
    const artifactIds = idsFor(await shiftedOffsetScan(root), "app.ts");

    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds }, { scan: shiftedOffsetScan });

    expect(plan.outcome).toBe("blocked");
    expect(plan.blockers[0]?.reason).toMatch(/could not be reproduced/i);
  });

  test("creates a sanitized PNG copy, preserves the original, verifies the copy, and removes only the copy on rollback", async () => {
    const { root, store } = await fixture();
    const image = join(root, "generated.png");
    await writeFile(image, PNG_WITH_AI_METADATA);
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "generated.png");
    expect(artifactIds.length).toBeGreaterThan(0);

    const blocked = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(blocked.outcome).toBe("blocked");
    expect(blocked.blockers[0]?.reason).toMatch(/metadata containers/i);

    const plan = await planRepositoryCleanup({
      path: root,
      artifact_ids: artifactIds,
      acknowledge_metadata_container_removal: true,
    });
    expect(plan).toMatchObject({ outcome: "ready", operations: [expect.objectContaining({ mode: "copy" })] });
    const applied = await applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
      confirm_rights_to_modify: true,
    }, { storeRoot: store });
    const cleaned = join(root, "generated.codeinspectus-clean.png");
    expect(await readFile(image)).toEqual(PNG_WITH_AI_METADATA);
    expect((await scanRepositoryTrust(cleaned)).artifacts).toEqual([]);
    expect(applied.operations[0]).toMatchObject({ destination_file: "generated.codeinspectus-clean.png", targeted_artifacts_resolved: true });

    await rollbackRepositoryCleanup({ cleanup_id: applied.cleanup_id, confirm_rollback: true }, { storeRoot: store });
    await expect(stat(cleaned)).rejects.toMatchObject({ code: "ENOENT" });
    expect(await readFile(image)).toEqual(PNG_WITH_AI_METADATA);
  });

  test("blocks protected legal records and refuses rollback over post-clean user changes", async () => {
    const { root, store } = await fixture();
    const notice = join(root, "NOTICE");
    await writeFile(notice, "// Generated by Claude Code\n", "utf8");
    const protectedScan = await scanRepositoryTrust(root);
    const protectedArtifact = protectedScan.artifacts.find((artifact) => artifact.location.file === "NOTICE")!;
    expect(protectedArtifact.remediation).toMatchObject({ protected_record: true, eligible: false });
    const blocked = await planRepositoryCleanup({ path: root, artifact_ids: [protectedArtifact.artifact_id] });
    expect(blocked.outcome).toBe("blocked");

    const source = join(root, "app.ts");
    await writeFile(source, "const user\u200Bname = true;\n", "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    const applied = await applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
    }, { storeRoot: store });
    await writeFile(source, "const username = 'changed-after-cleanup';\n", "utf8");
    const refused = await rollbackRepositoryCleanup({ cleanup_id: applied.cleanup_id, confirm_rollback: true }, { storeRoot: store });
    expect(refused.outcome).toBe("rollback_refused");
    expect(await readFile(source, "utf8")).toContain("changed-after-cleanup");
  });

  test("automatically restores earlier operations and records a failure audit when a later operation is interrupted", async () => {
    const { root, store } = await fixture();
    const first = join(root, "first.ts");
    const second = join(root, "second.ts");
    const markedFirst = "const first\u200BValue = true;\n";
    const markedSecond = "const second\u200BValue = true;\n";
    await writeFile(first, markedFirst, "utf8");
    await writeFile(second, markedSecond, "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = before.artifacts.filter((artifact) => artifact.remediation.eligible).map((artifact) => artifact.artifact_id);
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    expect(plan.operations).toHaveLength(2);
    const cleanupUuid = "22222222-2222-4222-8222-222222222222";

    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
    }, {
      storeRoot: store,
      randomId: () => cleanupUuid,
      beforeOperation: (_operation, index) => { if (index === 1) throw new Error("simulated interruption"); },
    })).rejects.toThrow(/automatic rollback completed.*simulated interruption/i);

    expect(await readFile(first, "utf8")).toBe(markedFirst);
    expect(await readFile(second, "utf8")).toBe(markedSecond);
    const audit = JSON.parse(await readFile(join(store, `cleanup-${cleanupUuid}`, "audit.json"), "utf8"));
    expect(audit).toMatchObject({ outcome: "failed_rolled_back", rollback_errors: [] });
    expect(JSON.stringify(audit)).not.toContain(markedFirst);
  });

  test("recovers an apply interrupted mid-way from the persisted journal after a restart", async () => {
    const { root, store } = await fixture();
    const originals = new Map([
      [join(root, "a.ts"), "const first​Value = true;\n"],
      [join(root, "b.ts"), "const second​Value = true;\n"],
    ]);
    for (const [path, content] of originals) await writeFile(path, content, "utf8");
    const artifactIds = (await scanRepositoryTrust(root)).artifacts.filter((item) => item.remediation.eligible).map((item) => item.artifact_id);
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    const cleanupId = "cleanup-33333333-3333-4333-8333-333333333333";
    let reachKillPoint!: () => void;
    let kill!: (error: Error) => void;
    const killPoint = new Promise<void>((resolve) => { reachKillPoint = resolve; });
    const killed = new Promise<void>((_resolve, reject) => { kill = reject; });

    const applying = applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true }, {
      storeRoot: store,
      randomId: () => cleanupId.slice("cleanup-".length),
      beforeOperation: async (_operation, index) => { if (index === 1) { reachKillPoint(); await killed; } },
    });
    await killPoint;
    // Simulated server restart: only the managed store survives.
    resetCleanupRuntimeStateForTests();
    const changed = [];
    for (const [path, content] of originals) if (await readFile(path, "utf8") !== content) changed.push(path);
    expect(changed).toHaveLength(1);

    const remaining = (await scanRepositoryTrust(root)).artifacts.filter((item) => item.remediation.eligible).map((item) => item.artifact_id);
    const blocked = await planRepositoryCleanup({ path: root, artifact_ids: remaining }, { storeRoot: store });
    expect(blocked.outcome).toBe("blocked");
    expect(blocked.blockers[0]?.reason).toContain(cleanupId);

    const recovered = await rollbackRepositoryCleanup({ cleanup_id: cleanupId, confirm_rollback: true }, { storeRoot: store });
    expect(recovered.outcome).toBe("rolled_back");
    for (const [path, content] of originals) expect(await readFile(path, "utf8")).toBe(content);

    kill(new Error("process killed"));
    await expect(applying).rejects.toThrow(/process killed/);
    for (const [path, content] of originals) expect(await readFile(path, "utf8")).toBe(content);
  });

  test("keeps restoring earlier operations when one automatic restore is refused", async () => {
    const { root, store } = await fixture();
    await writeFile(join(root, "a.ts"), "const first​Value = true;\n", "utf8");
    await writeFile(join(root, "b.ts"), "const second​Value = true;\n", "utf8");
    const artifactIds = (await scanRepositoryTrust(root)).artifacts.filter((item) => item.remediation.eligible).map((item) => item.artifact_id);
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    const [firstFile, secondFile] = plan.operations.map((operation) => join(root, operation.file));
    const firstOriginal = await readFile(firstFile!, "utf8");
    let scans = 0;

    await expect(applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true }, {
      storeRoot: store,
      scan: async (target) => {
        if (++scans === 2) {
          await writeFile(secondFile!, "const userEdit = true;\n", "utf8");
          throw new Error("simulated validator failure");
        }
        return scanRepositoryTrust(target);
      },
    })).rejects.toThrow(/requires review/i);

    expect(await readFile(firstFile!, "utf8")).toBe(firstOriginal);
    expect(await readFile(secondFile!, "utf8")).toBe("const userEdit = true;\n");
    const [cleanupId] = await readdir(store);
    const audit = JSON.parse(await readFile(join(store, cleanupId!, "audit.json"), "utf8"));
    expect(audit).toMatchObject({ outcome: "failed_rollback_incomplete" });
    expect(audit.rollback_errors).toHaveLength(1);

    const remaining = (await scanRepositoryTrust(root)).artifacts.filter((item) => item.remediation.eligible).map((item) => item.artifact_id);
    const blocked = await planRepositoryCleanup({ path: root, artifact_ids: remaining }, { storeRoot: store });
    expect(blocked.outcome).toBe("blocked");
    expect(blocked.blockers[0]?.reason).toContain(cleanupId!);

    const retry = await rollbackRepositoryCleanup({ cleanup_id: cleanupId!, confirm_rollback: true }, { storeRoot: store });
    expect(retry.outcome).toBe("rollback_refused");
    // A reviewed (refused) rollback releases the planning lock.
    expect((await planRepositoryCleanup({ path: root, artifact_ids: remaining }, { storeRoot: store })).blockers
      .some((item) => item.reason.includes(cleanupId!))).toBe(false);
    expect(await readFile(secondFile!, "utf8")).toBe("const userEdit = true;\n");
  });

  test("refuses to write through a parent directory swapped for a symlink after planning", async () => {
    const { root, store } = await fixture();
    const outside = await mkdtemp(join(tmpdir(), "codeinspectus-v33-outside-"));
    cleanup.push(outside);
    const marked = "const user​name = 1;\n";
    await mkdir(join(root, "sub"));
    await writeFile(join(root, "sub", "app.ts"), marked, "utf8");
    const artifactIds = idsFor(await scanRepositoryTrust(root), "sub/app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    await writeFile(join(outside, "app.ts"), marked, "utf8");

    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true,
    }, {
      storeRoot: store,
      // Race window: the parent is swapped right after the fresh pre-apply rescan, before preimages are read.
      scan: async (target) => {
        const document = await scanRepositoryTrust(target);
        if (!(await lstat(join(root, "sub")).then((entry) => entry.isSymbolicLink()))) {
          await rename(join(root, "sub"), join(root, "sub-real"));
          await symlink(outside, join(root, "sub"));
        }
        return document;
      },
    })).rejects.toThrow(/parent directory/i);
    expect(await readFile(join(outside, "app.ts"), "utf8")).toBe(marked);
    expect(await readFile(join(root, "sub-real", "app.ts"), "utf8")).toBe(marked);
  });

  test("lets only one of two concurrent applies of the same plan run", async () => {
    const { root, store } = await fixture();
    const source = join(root, "app.ts");
    await writeFile(source, "const user\u200Bname = 1;\n", "utf8");
    const ids = idsFor(await scanRepositoryTrust(root), "app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: ids });
    const input = { plan_id: plan.plan_id, approved_artifact_ids: ids, confirm_cleanup: true };

    const results = await Promise.allSettled([
      applyRepositoryCleanup(input, { storeRoot: store }),
      applyRepositoryCleanup(input, { storeRoot: store }),
    ]);

    expect(results.filter((item) => item.status === "fulfilled")).toHaveLength(1);
    expect(await readFile(source, "utf8")).toBe("const username = 1;\n");
  });

  test("a second plan for the same asset never removes the first plan's clean copy", async () => {
    const { root, store } = await fixture();
    await writeFile(join(root, "generated.png"), PNG_WITH_AI_METADATA);
    const ids = idsFor(await scanRepositoryTrust(root), "generated.png");
    const options = { path: root, artifact_ids: ids, acknowledge_metadata_container_removal: true };
    const first = await planRepositoryCleanup(options);
    const second = await planRepositoryCleanup(options);
    const approve = (planId: string) => ({ plan_id: planId, approved_artifact_ids: ids, confirm_cleanup: true, confirm_rights_to_modify: true });

    await applyRepositoryCleanup(approve(first.plan_id), { storeRoot: store });
    await expect(applyRepositoryCleanup(approve(second.plan_id), { storeRoot: store })).rejects.toThrow();

    expect((await stat(join(root, first.operations[0]!.destination_file!))).isFile()).toBe(true);
  });

  test("serializes applies of different plans for the same repository", async () => {
    const { root, store } = await fixture();
    const source = join(root, "app.ts");
    await writeFile(source, "const user\u200Bname = 1;\n", "utf8");
    const ids = idsFor(await scanRepositoryTrust(root), "app.ts");
    const first = await planRepositoryCleanup({ path: root, artifact_ids: ids });
    const second = await planRepositoryCleanup({ path: root, artifact_ids: ids });

    const results = await Promise.allSettled([first, second].map((plan) =>
      applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: ids, confirm_cleanup: true }, { storeRoot: store })));

    expect(results.filter((item) => item.status === "fulfilled")).toHaveLength(1);
    expect(await readFile(source, "utf8")).toBe("const username = 1;\n");
  });

  test("a failed apply's automatic rollback never undoes another apply's edit", async () => {
    const { root, store } = await fixture();
    await mkdir(join(root, "pkg"));
    const source = join(root, "pkg", "app.ts");
    await writeFile(source, "const user\u200Bname = 1;\n", "utf8");
    const outerIds = idsFor(await scanRepositoryTrust(root), "pkg/app.ts");
    const innerIds = idsFor(await scanRepositoryTrust(join(root, "pkg")), "app.ts");
    const outer = await planRepositoryCleanup({ path: root, artifact_ids: outerIds });
    const inner = await planRepositoryCleanup({ path: join(root, "pkg"), artifact_ids: innerIds });
    let innerReady!: () => void;
    let outerDone!: () => void;
    const innerAtWrite = new Promise<void>((resolve) => { innerReady = resolve; });
    const outerFinished = new Promise<void>((resolve) => { outerDone = resolve; });

    // Both applies verify the same preimage; the outer one writes first, then the inner one tries.
    const innerApply = applyRepositoryCleanup({ plan_id: inner.plan_id, approved_artifact_ids: innerIds, confirm_cleanup: true }, {
      storeRoot: join(store, "inner"),
      beforeOperation: async () => { innerReady(); await outerFinished; },
    });
    await innerAtWrite;
    await applyRepositoryCleanup({ plan_id: outer.plan_id, approved_artifact_ids: outerIds, confirm_cleanup: true }, { storeRoot: join(store, "outer") });
    outerDone();
    await expect(innerApply).rejects.toThrow();

    expect(await readFile(source, "utf8")).toBe("const username = 1;\n");
  });

  // chmod cannot make a directory read-only on Windows, so the marker write cannot be made to fail there.
  test.skipIf(process.platform === "win32")("removes its own clean copy when the created marker cannot be recorded", async () => {
    const { root, store } = await fixture();
    await writeFile(join(root, "generated.png"), PNG_WITH_AI_METADATA);
    const ids = idsFor(await scanRepositoryTrust(root), "generated.png");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: ids, acknowledge_metadata_container_removal: true });
    const cleanupId = "cleanup-44444444-4444-4444-8444-444444444444";
    const record = join(store, cleanupId);

    try {
      await expect(applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: ids, confirm_cleanup: true, confirm_rights_to_modify: true }, {
        storeRoot: store,
        randomId: () => cleanupId.slice("cleanup-".length),
        beforeOperation: async () => { await chmod(record, 0o500); },
      })).rejects.toThrow();
    } finally {
      await chmod(record, 0o700);
    }

    await expect(stat(join(root, plan.operations[0]!.destination_file!))).rejects.toThrow(/ENOENT/);
  });

  test("a corrupt audit record keeps planning blocked instead of throwing, and a failed rollback releases it", async () => {
    const { root, store } = await fixture();
    await writeFile(join(root, "app.ts"), "const user\u200Bname = 1;\n", "utf8");
    const ids = idsFor(await scanRepositoryTrust(root), "app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: ids });
    const applied = await applyRepositoryCleanup({ plan_id: plan.plan_id, approved_artifact_ids: ids, confirm_cleanup: true }, { storeRoot: store });
    await writeFile(join(store, applied.cleanup_id, "audit.json"), "{\"trunc", { mode: 0o600 });
    await rm(join(store, applied.cleanup_id, "backups"), { recursive: true, force: true });
    await writeFile(join(root, "other.ts"), "const other\u200Bname = 1;\n", "utf8");
    const otherIds = idsFor(await scanRepositoryTrust(root), "other.ts");

    const blocked = await planRepositoryCleanup({ path: root, artifact_ids: otherIds }, { storeRoot: store });
    expect(blocked.blockers[0]?.reason).toContain(applied.cleanup_id);

    await expect(rollbackRepositoryCleanup({ cleanup_id: applied.cleanup_id, confirm_rollback: true }, { storeRoot: store })).rejects.toThrow(/did not complete/);
    const released = await planRepositoryCleanup({ path: root, artifact_ids: otherIds }, { storeRoot: store });
    expect(released.outcome).toBe("ready");
  });

  test("rejects duplicate artifact IDs in plan and approval scope", async () => {
    const { root, store } = await fixture();
    await writeFile(join(root, "app.ts"), "const user​name = 1;\n", "utf8");
    const [id] = idsFor(await scanRepositoryTrust(root), "app.ts");

    await expect(planRepositoryCleanup({ path: root, artifact_ids: [id!, id!] })).rejects.toThrow(/unique/i);
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: [id!] });
    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id, approved_artifact_ids: [id!, id!], confirm_cleanup: true,
    }, { storeRoot: store })).rejects.toThrow(/unique/i);
  });

  test("automatically restores applied bytes when post-clean validation fails", async () => {
    const { root, store } = await fixture();
    const source = join(root, "app.ts");
    const original = "const post​Clean = true;\n";
    await writeFile(source, original, "utf8");
    const before = await scanRepositoryTrust(root);
    const artifactIds = idsFor(before, "app.ts");
    const plan = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds });
    let scans = 0;

    await expect(applyRepositoryCleanup({
      plan_id: plan.plan_id,
      approved_artifact_ids: artifactIds,
      confirm_cleanup: true,
    }, {
      storeRoot: store,
      scan: async (target) => {
        scans++;
        if (scans === 2) throw new Error("simulated validator failure");
        return scanRepositoryTrust(target);
      },
    })).rejects.toThrow(/automatic rollback completed.*simulated validator failure/i);

    expect(await readFile(source, "utf8")).toBe(original);
    const [cleanupId] = (await readdir(store)).filter((name) => name.startsWith("cleanup-"));
    const audit = JSON.parse(await readFile(join(store, cleanupId!, "audit.json"), "utf8"));
    expect(audit).toMatchObject({ outcome: "failed_rolled_back", failure: "simulated validator failure" });
    // Nothing it applied remains, so an explicit rollback must not act on coincidentally equal bytes.
    await expect(rollbackRepositoryCleanup({ cleanup_id: cleanupId!, confirm_rollback: true }, { storeRoot: store }))
      .rejects.toThrow(/already rolled back automatically/);
  });

  describe("C2PA copy cleanup end to end", () => {
    const manifest = Buffer.from("jumbc2pa-manifest-store");
    // Deterministic stand-in for the optional official reader: a manifest is present and valid
    // exactly when the manifest bytes are present.
    const c2paScan = (target: string) => scanRepositoryTrust(target, {
      aiProvenance: {
        c2paReader: async (asset) => asset.buffer.includes(manifest)
          ? { present: true, embedded: true, validationState: "Valid", manifestCount: 1, claimGenerator: "test-generator" }
          : { present: false },
      },
    });
    const riff = (id: string, payload: Buffer): Buffer => {
      const header = Buffer.alloc(8);
      header.write(id, 0, "ascii");
      header.writeUInt32LE(payload.length, 4);
      return Buffer.concat([header, payload, payload.length % 2 ? Buffer.alloc(1) : Buffer.alloc(0)]);
    };
    const isoBox = (type: string, payload: Buffer): Buffer => {
      const header = Buffer.alloc(8);
      header.writeUInt32BE(8 + payload.length, 0);
      header.write(type, 4, "ascii");
      return Buffer.concat([header, payload]);
    };
    const wav = (): Buffer => {
      const body = Buffer.concat([riff("fmt ", Buffer.alloc(16, 1)), riff("C2PA", manifest), riff("data", Buffer.from("PCM!"))]);
      const header = Buffer.from("RIFF\0\0\0\0WAVE", "ascii");
      header.writeUInt32LE(body.length + 4, 4);
      return Buffer.concat([header, body]);
    };
    const mp4 = (): Buffer => Buffer.concat([
      isoBox("ftyp", Buffer.from("isom0000")),
      isoBox("uuid", Buffer.concat([Buffer.from("d8fec3d61b0e483c92975828877ec481", "hex"), manifest])),
      isoBox("mdat", Buffer.from("SAMPLES")),
    ]);
    const mp3 = (): Buffer => {
      const tag = Buffer.concat([Buffer.from("ID3"), Buffer.from([4, 0, 0, 0, 0, 0, manifest.length]), manifest]);
      return Buffer.concat([tag, Buffer.from([0xff, 0xfb, 0x90, 0x64, 1, 2, 3, 4])]);
    };
    const jpeg = (): Buffer => {
      const app11 = Buffer.concat([Buffer.from([0xff, 0xeb]), Buffer.from([0, manifest.length + 2]), manifest]);
      return Buffer.concat([Buffer.from([0xff, 0xd8]), app11, Buffer.from([0xff, 0xda, 0x00, 0x02, 9, 8, 0xff, 0xd9])]);
    };

    test.each([["clip.wav", wav], ["clip.mp4", mp4], ["clip.mp3", mp3], ["photo.jpg", jpeg]] as const)(
      "gates, copies, verifies, and rolls back %s without touching the original",
      async (file, build) => {
        const { root, store } = await fixture();
        const original = build();
        await writeFile(join(root, file), original);
        const artifactIds = idsFor(await c2paScan(root), file);
        expect(artifactIds).toHaveLength(1);

        const noAck = await planRepositoryCleanup({ path: root, artifact_ids: artifactIds }, { scan: c2paScan });
        expect(noAck.blockers[0]?.reason).toMatch(/acknowledge_metadata_container_removal/);
        const containerOnly = await planRepositoryCleanup({
          path: root, artifact_ids: artifactIds, acknowledge_metadata_container_removal: true,
        }, { scan: c2paScan });
        expect(containerOnly.blockers[0]?.reason).toMatch(/acknowledge_provenance_copy/);
        const plan = await planRepositoryCleanup({
          path: root, artifact_ids: artifactIds, acknowledge_metadata_container_removal: true, acknowledge_provenance_copy: true,
        }, { scan: c2paScan });
        expect(plan).toMatchObject({ outcome: "ready", approval: { rights_confirmation_required: true } });
        expect(plan.operations[0]).toMatchObject({ action: "create_sanitized_asset_copy", mode: "copy" });

        const applied = await applyRepositoryCleanup({
          plan_id: plan.plan_id, approved_artifact_ids: artifactIds, confirm_cleanup: true, confirm_rights_to_modify: true,
        }, { storeRoot: store, scan: c2paScan });
        const copy = join(root, plan.operations[0]!.destination_file!);
        expect(applied.verification).toMatchObject({ same_validators_ran: true, targeted_artifacts_resolved: true });
        expect(await readFile(join(root, file))).toEqual(original);
        expect((await readFile(copy)).includes(manifest)).toBe(false);

        resetCleanupRuntimeStateForTests();
        const rolledBack = await rollbackRepositoryCleanup({ cleanup_id: applied.cleanup_id, confirm_rollback: true }, { storeRoot: store, scan: c2paScan });
        expect(rolledBack.outcome).toBe("rolled_back");
        await expect(stat(copy)).rejects.toThrow(/ENOENT/);
        expect(await readFile(join(root, file))).toEqual(original);
      },
    );
  });

  describe("ISO BMFF chunk offsets", () => {
    const box = (type: string, ...payload: Buffer[]): Buffer => {
      const body = Buffer.concat(payload);
      const header = Buffer.alloc(8);
      header.writeUInt32BE(8 + body.length, 0);
      header.write(type, 4, "ascii");
      return Buffer.concat([header, body]);
    };
    const ftyp = box("ftyp", Buffer.from("isom0000"));
    const c2paUuid = box("uuid", Buffer.from("d8fec3d61b0e483c92975828877ec481", "hex"), Buffer.from("\0\0\0\0manifest\0jumbc2pa"));
    const sample = Buffer.from("SAMPLEDATA");
    const offsetTable = (type: "stco" | "co64", offset: number): Buffer => {
      const body = Buffer.alloc(type === "stco" ? 12 : 16);
      body.writeUInt32BE(1, 4);
      if (type === "stco") body.writeUInt32BE(offset, 8);
      else body.writeBigUInt64BE(BigInt(offset), 8);
      return box(type, body);
    };
    const moov = (type: "stco" | "co64", offset: number): Buffer =>
      box("moov", box("udta", Buffer.from("meta-claude")), box("trak", box("mdia", box("minf", box("stbl", offsetTable(type, offset))))));
    const faststart = (type: "stco" | "co64"): Buffer => {
      const payloadOffset = ftyp.length + c2paUuid.length + moov(type, 0).length + 8;
      return Buffer.concat([ftyp, c2paUuid, moov(type, payloadOffset), box("mdat", sample)]);
    };
    const firstChunkOffset = (file: Buffer, type: "stco" | "co64"): number => {
      const index = file.indexOf(Buffer.from(type));
      return type === "stco" ? file.readUInt32BE(index + 12) : Number(file.readBigUInt64BE(index + 12));
    };

    test.each(["stco", "co64"] as const)("rewrites %s entries so they still address the media payload", (type) => {
      const cleaned = sanitizeAsset("mp4", faststart(type));

      expect(cleaned.includes(Buffer.from("udta"))).toBe(false);
      expect(cleaned.includes(Buffer.from("jumbc2pa"))).toBe(false);
      const offset = firstChunkOffset(cleaned, type);
      expect(cleaned.subarray(offset, offset + sample.length)).toEqual(sample);
    });

    test("refuses fragmented files whose offsets it cannot rewrite", () => {
      const fragmented = Buffer.concat([faststart("stco"), box("moof", box("mfhd", Buffer.alloc(8)))]);

      expect(() => sanitizeAsset("mp4", fragmented)).toThrow(/fragmented|not supported/i);
    });
  });

  test("removes WAV C2PA and _PMX XMP chunks while keeping fmt and data", () => {
    const chunk = (id: string, payload: Buffer): Buffer => {
      const header = Buffer.alloc(8);
      header.write(id, 0, "ascii");
      header.writeUInt32LE(payload.length, 4);
      return Buffer.concat([header, payload, payload.length % 2 ? Buffer.alloc(1) : Buffer.alloc(0)]);
    };
    const fmt = chunk("fmt ", Buffer.alloc(16, 1));
    const data = chunk("data", Buffer.from("PCMSAMPLES"));
    const body = Buffer.concat([fmt, chunk("C2PA", Buffer.from("jumbc2pa-manifest")), chunk("_PMX", Buffer.from("<x:xmpmeta>Claude</x:xmpmeta>")), data]);
    const header = Buffer.from("RIFF\0\0\0\0WAVE", "ascii");
    header.writeUInt32LE(body.length + 4, 4);

    const cleaned = sanitizeAsset("wav", Buffer.concat([header, body]));

    expect(cleaned.subarray(12)).toEqual(Buffer.concat([fmt, data]));
    expect(cleaned.readUInt32LE(4)).toBe(fmt.length + data.length + 4);
  });

  test("sanitizers reject malformed assets and preserve encoded payload boxes", () => {
    expect(() => sanitizeAsset("png", Buffer.from("not-png"))).toThrow(/PNG signature/i);
    const ftyp = Buffer.from([0, 0, 0, 12, 0x66, 0x74, 0x79, 0x70, 0x69, 0x73, 0x6f, 0x6d]);
    const udta = Buffer.from([0, 0, 0, 12, 0x75, 0x64, 0x74, 0x61, 1, 2, 3, 4]);
    const mdat = Buffer.from([0, 0, 0, 12, 0x6d, 0x64, 0x61, 0x74, 9, 8, 7, 6]);
    const cleaned = sanitizeAsset("mp4", Buffer.concat([ftyp, udta, mdat]));
    expect(cleaned.includes(udta)).toBe(false);
    expect(cleaned.subarray(-4)).toEqual(Buffer.from([9, 8, 7, 6]));

    const jpegApp1 = Buffer.from([0xff, 0xd8, 0xff, 0xe1, 0x00, 0x06, 1, 2, 3, 4, 0xff, 0xda, 0x00, 0x02, 9, 8, 0xff, 0xd9]);
    const jpegCleaned = sanitizeAsset("jpg", jpegApp1);
    expect(jpegCleaned).toEqual(Buffer.from([0xff, 0xd8, 0xff, 0xda, 0x00, 0x02, 9, 8, 0xff, 0xd9]));

    const mp3Audio = Buffer.from([0xff, 0xfb, 1, 2, 3]);
    const mp3 = Buffer.concat([Buffer.from([0x49, 0x44, 0x33, 4, 0, 0, 0, 0, 0, 0]), mp3Audio, Buffer.concat([Buffer.from("TAG"), Buffer.alloc(125)])]);
    expect(sanitizeAsset("mp3", mp3)).toEqual(mp3Audio);

    const fmt = Buffer.from([0x66, 0x6d, 0x74, 0x20, 4, 0, 0, 0, 1, 2, 3, 4]);
    const list = Buffer.from([0x4c, 0x49, 0x53, 0x54, 4, 0, 0, 0, 5, 6, 7, 8]);
    const wavHeader = Buffer.from([0x52, 0x49, 0x46, 0x46, 0, 0, 0, 0, 0x57, 0x41, 0x56, 0x45]);
    const wavCleaned = sanitizeAsset("wav", Buffer.concat([wavHeader, fmt, list]));
    expect(wavCleaned.subarray(12)).toEqual(fmt);
    expect(wavCleaned.readUInt32LE(4)).toBe(fmt.length + 4);
  });
});
