import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { repositoryTrustDocumentSchema } from "./schemas.js";
import { scanRepositoryTrust } from "./index.js";

const cleanup: string[] = [];

afterEach(async () => {
  await Promise.all(cleanup.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

describe("V3.2 repository-trust aggregation", () => {
  test("combines V3.1 source integrity with V3.2 provenance while keeping statistical detection unavailable", async () => {
    const root = await mkdtemp(join(tmpdir(), "codeinspectus-repository-trust-"));
    cleanup.push(root);
    await writeFile(join(root, "generated.ts"), "// Generated by Claude Code\nconst admin\u200BRole = true;\n", "utf8");

    const document = await scanRepositoryTrust(root, {
      aiProvenance: {
        gitHistoryReader: async () => ({ applicable: false, truncated: false, records: [] }),
      },
    });

    expect(repositoryTrustDocumentSchema.parse(document)).toEqual(document);
    expect(document.coverage.state).toBe("partial");
    expect(document.coverage.capabilities).toEqual(expect.arrayContaining([
      expect.objectContaining({ capability: "source_integrity", state: "ran" }),
      expect.objectContaining({ capability: "explicit_ai_attribution", state: "ran" }),
      expect.objectContaining({ capability: "content_provenance", state: "not_applicable" }),
      expect.objectContaining({ capability: "statistical_watermark", state: "unavailable" }),
    ]));
    expect(document.artifacts).toEqual(expect.arrayContaining([
      expect.objectContaining({ kind: "source_integrity", marker_class: "unicode_zero_width_token" }),
      expect.objectContaining({ kind: "explicit_ai_attribution", marker_class: "explicit_generator_attribution" }),
    ]));
    expect(document.summary.total).toBe(document.artifacts.length);
  });
});
