import { mkdir, mkdtemp, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, test } from "vitest";

import {
  PUB_LOCKFILE_LIMITS,
  discoverPubLockfiles,
  loadPubLockfiles,
  parsePubLockfile,
} from "./lockfile.js";

const SHA = "a".repeat(64);
const roots: string[] = [];

async function tempRoot(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "codeinspectus-pub-lock-"));
  roots.push(root);
  return root;
}

async function writeLockfile(path: string, content = "packages: {}\n"): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

function packageBlock(name: string, overrides: {
  dependency?: string;
  description?: string;
  source?: string;
  version?: string;
} = {}): string {
  return [
    `  ${name}:`,
    `    dependency: ${overrides.dependency ?? "transitive"}`,
    `    description: ${overrides.description ?? name}`,
    `    source: ${overrides.source ?? "hosted"}`,
    `    version: ${overrides.version ?? "\"1.0.0\""}`,
  ].join("\n");
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("parsePubLockfile", () => {
  test("parses official, custom-hosted, git, path, and SDK dependencies without losing SBOM data", () => {
    const parsed = parsePubLockfile({
      path: "apps/mobile/pubspec.lock",
      content: [
        "# Generated by pub",
        "packages:",
        "  archive:",
        "    dependency: \"direct main\"",
        "    description:",
        "      name: archive",
        `      sha256: ${SHA.toUpperCase()}`,
        "      url: \"https://pub.dev\"",
        "    source: hosted",
        "    version: \"3.4.9\"",
        "  custom_pkg:",
        "    dependency: \"direct dev\"",
        "    description:",
        "      name: custom_pkg",
        "      sha256: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'",
        "      url: 'https://packages.example.test/pub'",
        "    source: hosted",
        "    version: '2.0.0'",
        "  flutter:",
        "    dependency: \"direct overridden\"",
        "    description: flutter",
        "    source: sdk",
        "    version: \"0.0.0\"",
        "  git_dep:",
        "    dependency: transitive",
        "    description:",
        "      path: .",
        "      ref: HEAD",
        "      resolved-ref: abc123",
        "      url: \"git@github.com:example/git_dep.git\"",
        "    source: git",
        "    version: \"1.2.3\"",
        "  old_official:",
        "    dependency: transitive",
        "    description:",
        "      name: old_official",
        "      url: \"https://pub.dartlang.org/\"",
        "    source: hosted",
        "    version: \"1.0.0\"",
        "  path_dep:",
        "    dependency: transitive",
        "    description:",
        "      path: ../path_dep",
        "      relative: true",
        "    source: path",
        "    version: \"4.5.6\"",
        "sdks:",
        "  dart: \">=3.5.0 <4.0.0\"",
        "  flutter: \">=3.24.0\"",
        "",
      ].join("\n"),
    });

    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.packages.map((pkg) => pkg.name)).toEqual([
      "archive",
      "custom_pkg",
      "flutter",
      "git_dep",
      "old_official",
      "path_dep",
    ]);
    expect(parsed.packages[0]).toMatchObject({
      version: "3.4.9",
      version_line: 10,
      dependency: "direct main",
      direct: true,
      source: "hosted",
      registry: "official",
      lockfile_path: "apps/mobile/pubspec.lock",
      description: { name: "archive", url: "https://pub.dev", sha256: SHA },
    });
    expect(parsed.packages.find((pkg) => pkg.name === "custom_pkg")).toMatchObject({
      direct: true,
      registry: "custom",
      description: { name: "custom_pkg", url: "https://packages.example.test/pub" },
    });
    expect(parsed.packages.find((pkg) => pkg.name === "git_dep")).toMatchObject({
      direct: false,
      source: "git",
      registry: "non_hosted",
      description: { url: "git@github.com:example/git_dep.git" },
    });
    expect(parsed.packages.find((pkg) => pkg.name === "path_dep")).toMatchObject({
      source: "path",
      description: {},
    });
    expect(parsed.packages.find((pkg) => pkg.name === "flutter")).toMatchObject({
      dependency: "direct overridden",
      source: "sdk",
      description: { name: "flutter" },
    });
    expect(parsed.packages.find((pkg) => pkg.name === "old_official")?.registry).toBe("official");
  });

  test("supports the legacy scalar hosted description and an explicitly empty generated lockfile", () => {
    const legacy = parsePubLockfile({
      path: "pubspec.lock",
      content: `packages:\n${packageBlock("meta")}\n`,
    });
    expect(legacy).toMatchObject({
      ok: true,
      packages: [{ name: "meta", registry: "official", description: { name: "meta" } }],
    });

    expect(parsePubLockfile({
      path: "pubspec.lock",
      content: "\uFEFFpackages: {}\r\nsdks:\r\n  dart: \">=3.0.0 <4.0.0\"\r\n",
    })).toEqual({ ok: true, packages: [] });
  });

  test.each([
    ["tabs", "packages:\n\tbad:\n"],
    ["anchor", "packages: &packages\n"],
    ["alias", "packages:\n  bad:\n    dependency: transitive\n    description: *shared\n"],
    ["merge key", "packages:\n  bad:\n    <<: *shared\n"],
    ["duplicate package", `packages:\n${packageBlock("bad")}\n${packageBlock("bad")}\n`],
    [
      "duplicate field",
      `packages:\n${packageBlock("bad")}\n    version: \"2.0.0\"\n`,
    ],
    [
      "odd indentation",
      "packages:\n  bad:\n   dependency: transitive\n",
    ],
    [
      "missing required field",
      "packages:\n  bad:\n    dependency: transitive\n    description: bad\n    source: hosted\n",
    ],
    [
      "mismatched hosted name",
      "packages:\n  bad:\n    dependency: transitive\n    description:\n      name: other\n      url: \"https://pub.dev\"\n    source: hosted\n    version: \"1.0.0\"\n",
    ],
    [
      "unknown source",
      "packages:\n  bad:\n    dependency: transitive\n    description: bad\n    source: registry\n    version: \"1.0.0\"\n",
    ],
    ["flow list", "packages: []\n"],
    ["implicit empty map", "packages:\nsdks:\n  dart: \"3.5.0\"\n"],
    [
      "ambiguous nested mapping",
      "packages:\n  bad:\n    dependency: transitive\n    description:\n      name:\n        nested: value\n    source: hosted\n    version: \"1.0.0\"\n",
    ],
  ])("fails closed on %s YAML", (_case, content) => {
    const parsed = parsePubLockfile({ path: "pubspec.lock", content });
    expect(parsed.ok).toBe(false);
    if (parsed.ok) return;
    expect(parsed.error.message).not.toContain("unexpected");
  });

  test.each([
    ["uppercase package identity", packageBlock("Uppercase")],
    ["non-semantic version", packageBlock("bad_version", { version: '"latest"' })],
    ["leading-zero core version", packageBlock("bad_version", { version: '"01.2.3"' })],
    ["leading-zero numeric prerelease", packageBlock("bad_version", { version: '"1.2.3-dev.01"' })],
    ["whitespace version", packageBlock("bad_version", { version: '"1.2.3 bad"' })],
  ])("rejects %s instead of treating it as an eligible clean package", (_label, block) => {
    const result = parsePubLockfile({ path: "pubspec.lock", content: `packages:\n${block}\n` });
    expect(result.ok).toBe(false);
  });

  test("accepts Pub prerelease and build metadata boundaries", () => {
    const result = parsePubLockfile({
      path: "pubspec.lock",
      content: [
        "packages:",
        packageBlock("pre", { version: '"1.2.3-dev.0"' }),
        packageBlock("build", { version: '"1.2.3+4.abc"' }),
        "",
      ].join("\n"),
    });
    expect(result).toMatchObject({
      ok: true,
      packages: [
        { name: "build", version: "1.2.3+4.abc" },
        { name: "pre", version: "1.2.3-dev.0" },
      ],
    });
  });

  test("enforces independent byte and package-count parser bounds", () => {
    const oversized = parsePubLockfile({
      path: "pubspec.lock",
      content: "#".repeat(PUB_LOCKFILE_LIMITS.max_bytes_per_lockfile + 1),
    });
    expect(oversized).toMatchObject({ ok: false, error: { message: expect.stringMatching(/2 MiB/) } });

    const blocks = Array.from(
      { length: PUB_LOCKFILE_LIMITS.max_packages_per_lockfile + 1 },
      (_, index) => packageBlock(`p${index}`),
    );
    const tooMany = parsePubLockfile({
      path: "pubspec.lock",
      content: `packages:\n${blocks.join("\n")}\n`,
    });
    expect(tooMany).toMatchObject({
      ok: false,
      error: { message: expect.stringMatching(/package parser bound/) },
    });
  });
});

describe("Pub lockfile discovery and loading", () => {
  test("loads a direct pubspec.lock target", async () => {
    const root = await tempRoot();
    const path = join(root, "pubspec.lock");
    await writeLockfile(path, `packages:\n${packageBlock("meta")}\n`);

    const result = await loadPubLockfiles(path);
    expect(result.root).toBe(root);
    expect(result.lockfiles).toMatchObject([
      { path: "pubspec.lock", status: "parsed", packages: [{ name: "meta" }] },
    ]);
    expect(result.packages).toHaveLength(1);
  });

  test("discovers monorepo lockfiles deterministically and never follows ignored or symbolic-link paths", async () => {
    const root = await tempRoot();
    const outside = await tempRoot();
    await writeLockfile(join(root, "z_app", "pubspec.lock"));
    await writeLockfile(join(root, "a_app", "pubspec.lock"));
    await writeLockfile(join(root, "node_modules", "hidden", "pubspec.lock"));
    await writeLockfile(join(root, ".dart_tool", "pubspec.lock"));
    await writeLockfile(join(outside, "pubspec.lock"));
    await mkdir(join(root, "linked_file"), { recursive: true });
    await symlink(join(outside, "pubspec.lock"), join(root, "linked_file", "pubspec.lock"));
    await symlink(outside, join(root, "linked_directory"), "dir");

    const result = await discoverPubLockfiles(root);
    expect(result.lockfiles.map((lockfile) => lockfile.path)).toEqual([
      "a_app/pubspec.lock",
      "z_app/pubspec.lock",
    ]);
    expect(result.skipped.symlinked_lockfiles).toBe(1);
    expect(result.skipped.symlinked_paths).toBe(1);
    expect(result.notes.join(" ")).toMatch(/symbolic-link Pub lockfile linked_file\/pubspec\.lock/);
    expect(result.notes.join(" ")).toMatch(/symbolic-link path linked_directory/);
  });

  test("retains all package sources while exposing exact native-SCA exclusions", async () => {
    const root = await tempRoot();
    await writeLockfile(join(root, "pubspec.lock"), [
      "packages:",
      packageBlock("official"),
      "  custom:",
      "    dependency: transitive",
      "    description:",
      "      name: custom",
      "      url: \"https://pub.dev.example.test\"",
      "    source: hosted",
      "    version: \"1.0.0\"",
      packageBlock("from_git", { description: undefined, source: "git" })
        .replace("    description: from_git", "    description:\n      url: \"https://github.com/example/from_git.git\""),
      packageBlock("from_path", { description: undefined, source: "path" })
        .replace("    description: from_path", "    description:\n      path: ../from_path"),
      packageBlock("flutter", { dependency: "\"direct main\"", source: "sdk", version: "\"0.0.0\"" }),
      "",
    ].join("\n"));

    const result = await loadPubLockfiles(root);
    expect(result.packages.map((pkg) => [pkg.name, pkg.registry])).toEqual([
      ["custom", "custom"],
      ["flutter", "non_hosted"],
      ["from_git", "non_hosted"],
      ["from_path", "non_hosted"],
      ["official", "official"],
    ]);
    expect(result.skipped).toMatchObject({
      custom_hosted_packages: 1,
      git_packages: 1,
      path_packages: 1,
      sdk_packages: 1,
    });
    expect(result.notes.join(" ")).toMatch(
      /Retained 4 non-official dependency instance\(s\) for coverage and source accounting but excluded them from native Pub vulnerability matching and native Pub SBOM components/,
    );
  });

  test("keeps an existing malformed lockfile explicit instead of treating it as absent", async () => {
    const root = await tempRoot();
    await writeLockfile(join(root, "good", "pubspec.lock"));
    await writeLockfile(
      join(root, "bad", "pubspec.lock"),
      `packages:\n${packageBlock("duplicate")}\n  duplicate:\n`,
    );

    const result = await loadPubLockfiles(root);
    expect(result.lockfiles).toMatchObject([
      {
        path: "bad/pubspec.lock",
        status: "malformed",
        packages: [],
        error: expect.stringMatching(/duplicate package/),
      },
      { path: "good/pubspec.lock", status: "parsed" },
    ]);
    expect(result.skipped.malformed_lockfiles).toBe(1);
    expect(result.notes.join(" ")).toMatch(/Rejected malformed Pub lockfile bad\/pubspec\.lock/);
  });

  test("represents oversized lockfiles as bounded skipped results", async () => {
    const root = await tempRoot();
    await writeFile(
      join(root, "pubspec.lock"),
      Buffer.alloc(PUB_LOCKFILE_LIMITS.max_bytes_per_lockfile + 1, 32),
    );

    const result = await loadPubLockfiles(root);
    expect(result.lockfiles).toMatchObject([
      { path: "pubspec.lock", status: "skipped", error: expect.stringMatching(/2 MiB/) },
    ]);
    expect(result.skipped.oversized_lockfiles).toBe(1);
  });

  test("enforces deterministic discovery file-count and directory-depth bounds", async () => {
    const root = await tempRoot();
    for (let index = 0; index <= PUB_LOCKFILE_LIMITS.max_lockfiles; index++) {
      await writeLockfile(join(root, `package_${String(index).padStart(3, "0")}`, "pubspec.lock"));
    }
    let deepest = join(root, "deep");
    for (let index = 0; index <= PUB_LOCKFILE_LIMITS.max_directory_depth; index++) {
      deepest = join(deepest, `d${index}`);
    }
    await writeLockfile(join(deepest, "pubspec.lock"));

    const result = await discoverPubLockfiles(root);
    expect(result.lockfiles).toHaveLength(PUB_LOCKFILE_LIMITS.max_lockfiles);
    expect(result.skipped.lockfiles_beyond_limit).toBe(1);
    expect(result.skipped.directories_beyond_depth).toBe(1);
    expect(result.notes.join(" ")).toMatch(/256-file bound/);
    expect(result.notes.join(" ")).toMatch(/beyond depth 32/);
  });

  test("counts an unreadable subdirectory so coverage cannot report a complete run", async () => {
    const root = await tempRoot();
    const blocked = join(root, "blocked");
    await mkdir(blocked, { recursive: true });
    await writeLockfile(join(root, "pubspec.lock"));

    const result = await discoverPubLockfiles(root, {
      readDirectory: async (directory) => {
        if (directory === blocked) throw new Error("synthetic permission failure");
        return readdir(directory, { withFileTypes: true });
      },
    });

    expect(result.lockfiles).toHaveLength(1);
    expect(result.skipped.unreadable_directories).toBe(1);
    expect(result.notes.join(" ")).toMatch(/Skipped unreadable Pub lockfile directory blocked/);
  });

  test("rejects a direct symbolic-link lockfile target", async () => {
    const root = await tempRoot();
    const outside = await tempRoot();
    const real = join(outside, "pubspec.lock");
    const linked = join(root, "pubspec.lock");
    await writeLockfile(real);
    await symlink(real, linked);

    const result = await loadPubLockfiles(linked);
    expect(result.lockfiles).toEqual([]);
    expect(result.skipped.symlinked_lockfiles).toBe(1);
    expect(result.notes).toContain("Skipped symbolic-link Pub lockfile target.");
  });
});
