/** Read-only, bounded C# source loading for first-party native analyzers. */

import { constants, type BigIntStats } from "node:fs";
import { lstat, open, readdir, type FileHandle } from "node:fs/promises";
import { basename, dirname, extname, join, parse, relative, resolve } from "node:path";

export const CSHARP_MAX_SOURCE_BYTES = 2 * 1024 * 1024;
export const CSHARP_MAX_SOURCE_FILES = 10_000;
export const CSHARP_MAX_TOTAL_BYTES = 64 * 1024 * 1024;
export const CSHARP_MAX_DEPTH = 32;
export const CSHARP_MAX_DISCOVERY_ENTRIES = 50_000;

const MAX_LIMITATIONS = 24;
const IGNORED_DIRS = new Set([
  ".cache", ".git", ".hg", ".idea", ".svn", ".vs", ".vscode",
  "artifacts", "bin", "build", "coverage", "dist", "generated", "node_modules",
  "obj", "out", "packages", "publish", "target", "vendor",
]);
const NON_PRODUCTION_DIRS = new Set([
  "demo", "demos", "example", "examples", "fixture", "fixtures", "integration-test",
  "integration-tests", "sample", "samples", "test", "testdata", "tests",
]);

export interface CsharpDocument {
  path: string;
  content: string;
}

export interface CsharpProject {
  target: string;
  root: string;
  files: CsharpDocument[];
  limitations?: string[];
}

export type CsharpProjectInput = string | CsharpProject | Promise<CsharpProject>;

function sourcePath(path: string): boolean {
  return extname(path).toLowerCase() === ".cs";
}

function nonProductionSourceName(name: string): boolean {
  const lower = name.toLowerCase();
  return lower.startsWith("test") || lower.endsWith("test.cs") || lower.endsWith("tests.cs") ||
    lower.endsWith("spec.cs") || lower.endsWith("specs.cs");
}

function generatedSource(name: string, content: string): boolean {
  const lower = name.toLowerCase();
  if (
    lower.endsWith(".g.cs") || lower.endsWith(".g.i.cs") || lower.endsWith(".generated.cs") ||
    lower.endsWith(".designer.cs") || lower.endsWith(".assemblyattributes.cs")
  ) return true;
  const header = content.split(/\r?\n/, 10).join("\n");
  return /<auto-generated\b/i.test(header) ||
    /(?:generated|autogenerated).{0,100}(?:do not edit|do not modify)/is.test(header);
}

function collector(): { add: (value: string) => void; finish: () => string[] } {
  const values = new Set<string>();
  let omitted = 0;
  return {
    add(value) {
      if (values.size < MAX_LIMITATIONS - 1) values.add(value);
      else omitted++;
    },
    finish() {
      return [
        ...values,
        ...(omitted ? [`${omitted} additional C# source limitations omitted.`] : []),
      ].sort();
    },
  };
}

function normalized(path: string): string {
  return path.replace(/\\/g, "/");
}

function sameIdentity(left: BigIntStats, right: BigIntStats): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}

function unchangedFile(before: BigIntStats, after: BigIntStats): boolean {
  return sameIdentity(before, after) && before.size === after.size &&
    before.mtimeNs === after.mtimeNs && before.ctimeNs === after.ctimeNs;
}

async function hasSymbolicLinkAncestor(absoluteTarget: string): Promise<boolean> {
  const filesystemRoot = parse(absoluteTarget).root;
  const ancestors: string[] = [];
  let current = dirname(absoluteTarget);
  while (current !== filesystemRoot) {
    ancestors.push(current);
    const parent = dirname(current);
    if (parent === current) break;
    current = parent;
  }
  for (const ancestor of ancestors.reverse()) {
    const metadata = await lstat(ancestor).catch(() => undefined);
    if (!metadata) break;
    if (metadata.isSymbolicLink()) return true;
  }
  return false;
}

async function readCsharpFile(
  absolute: string,
  displayPath: string,
  remainingBytes: number,
): Promise<{ document?: CsharpDocument; bytes?: number; limitation?: string; totalExceeded?: boolean }> {
  let handle: FileHandle | undefined;
  try {
    const before = await lstat(absolute, { bigint: true });
    if (before.isSymbolicLink()) return { limitation: `Skipped symbolic-link C# source ${displayPath}.` };
    if (!before.isFile()) return {};
    if (before.size > BigInt(CSHARP_MAX_SOURCE_BYTES)) {
      return { limitation: `Skipped oversized C# source ${displayPath} (limit: ${CSHARP_MAX_SOURCE_BYTES} bytes).` };
    }
    if (before.size > BigInt(remainingBytes)) return { bytes: Number(before.size), totalExceeded: true };
    const noFollow = typeof constants.O_NOFOLLOW === "number" ? constants.O_NOFOLLOW : 0;
    handle = await open(absolute, constants.O_RDONLY | noFollow);
    const opened = await handle.stat({ bigint: true });
    if (!opened.isFile() || !sameIdentity(before, opened)) {
      return { limitation: `Skipped changed C# source ${displayPath}.` };
    }
    if (opened.size > BigInt(CSHARP_MAX_SOURCE_BYTES)) {
      return { limitation: `Skipped oversized C# source ${displayPath} (limit: ${CSHARP_MAX_SOURCE_BYTES} bytes).` };
    }
    if (opened.size > BigInt(remainingBytes)) return { bytes: Number(opened.size), totalExceeded: true };
    const size = Number(opened.size);
    const bytes = Buffer.alloc(size);
    let offset = 0;
    while (offset < size) {
      const { bytesRead } = await handle.read(bytes, offset, size - offset, offset);
      if (bytesRead === 0) return { limitation: `Skipped changed C# source ${displayPath}.` };
      offset += bytesRead;
    }
    if (!unchangedFile(opened, await handle.stat({ bigint: true }))) {
      return { bytes: size, limitation: `Skipped changed C# source ${displayPath}.` };
    }
    let content: string;
    try {
      content = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    } catch {
      return { bytes: size, limitation: `Skipped non-UTF-8 C# source ${displayPath}.` };
    }
    if (generatedSource(basename(absolute), content)) return { bytes: size };
    return { document: { path: normalized(displayPath), content }, bytes: size };
  } catch {
    return { limitation: `Skipped unreadable C# source ${displayPath}.` };
  } finally {
    await handle?.close().catch(() => undefined);
  }
}

async function loadUncached(target: string): Promise<CsharpProject> {
  const absoluteTarget = resolve(target);
  const limitations = collector();
  if (await hasSymbolicLinkAncestor(absoluteTarget)) {
    return {
      target: absoluteTarget,
      root: sourcePath(absoluteTarget) ? dirname(absoluteTarget) : absoluteTarget,
      files: [],
      limitations: ["Skipped C# source target because a symbolic-link ancestor would be followed; symbolic-link ancestors are never allowed."],
    };
  }
  const metadata = await lstat(absoluteTarget).catch(() => undefined);
  if (!metadata) return { target: absoluteTarget, root: absoluteTarget, files: [], limitations: ["C# source target was unreadable."] };
  if (metadata.isSymbolicLink()) {
    return { target: absoluteTarget, root: dirname(absoluteTarget), files: [], limitations: ["Skipped symbolic-link C# source target; symbolic links are never followed."] };
  }
  if (metadata.isFile()) {
    if (!sourcePath(absoluteTarget)) return { target: absoluteTarget, root: dirname(absoluteTarget), files: [] };
    const loaded = await readCsharpFile(absoluteTarget, basename(absoluteTarget), CSHARP_MAX_TOTAL_BYTES);
    if (loaded.limitation) limitations.add(loaded.limitation);
    return { target: absoluteTarget, root: dirname(absoluteTarget), files: loaded.document ? [loaded.document] : [], limitations: limitations.finish() };
  }
  if (!metadata.isDirectory()) return { target: absoluteTarget, root: absoluteTarget, files: [] };

  const files: CsharpDocument[] = [];
  let entriesInspected = 0;
  let totalBytes = 0;
  let stopped = false;
  async function walk(directory: string, depth: number): Promise<void> {
    if (stopped) return;
    if (depth > CSHARP_MAX_DEPTH) {
      limitations.add(`Skipped C# source below ${normalized(relative(absoluteTarget, directory)) || "."} beyond the ${CSHARP_MAX_DEPTH}-level depth bound.`);
      return;
    }
    const entries = await readdir(directory, { withFileTypes: true }).catch(() => undefined);
    if (!entries) {
      limitations.add(`Skipped unreadable C# source directory ${normalized(relative(absoluteTarget, directory)) || "."}.`);
      return;
    }
    entries.sort((left, right) => left.name.localeCompare(right.name));
    for (const entry of entries) {
      if (stopped) break;
      if (++entriesInspected > CSHARP_MAX_DISCOVERY_ENTRIES) {
        limitations.add(`Stopped C# source discovery at the ${CSHARP_MAX_DISCOVERY_ENTRIES}-entry bound.`);
        stopped = true;
        break;
      }
      const absolute = join(directory, entry.name);
      const display = normalized(relative(absoluteTarget, absolute));
      if (entry.isSymbolicLink()) {
        limitations.add(`Skipped symbolic-link C# source entry ${display}.`);
        continue;
      }
      if (entry.isDirectory()) {
        const lower = entry.name.toLowerCase();
        if (IGNORED_DIRS.has(lower) || NON_PRODUCTION_DIRS.has(lower)) continue;
        await walk(absolute, depth + 1);
        continue;
      }
      if (!entry.isFile() || !sourcePath(entry.name) || nonProductionSourceName(entry.name)) continue;
      if (files.length >= CSHARP_MAX_SOURCE_FILES) {
        limitations.add(`Stopped C# source discovery at the ${CSHARP_MAX_SOURCE_FILES}-file bound.`);
        stopped = true;
        break;
      }
      const loaded = await readCsharpFile(absolute, display, CSHARP_MAX_TOTAL_BYTES - totalBytes);
      if (loaded.limitation) limitations.add(loaded.limitation);
      if (loaded.totalExceeded) {
        limitations.add(`Stopped C# source discovery at the ${CSHARP_MAX_TOTAL_BYTES}-byte project bound.`);
        stopped = true;
        break;
      }
      totalBytes += loaded.bytes ?? 0;
      if (loaded.document) files.push(loaded.document);
    }
  }
  await walk(absoluteTarget, 0);
  return { target: absoluteTarget, root: absoluteTarget, files, limitations: limitations.finish() };
}

export function resolveCsharpProject(input: CsharpProjectInput): Promise<CsharpProject> {
  return typeof input === "string" ? loadUncached(input) : Promise.resolve(input);
}

export function createCachedCsharpProjectLoader(target: string): () => Promise<CsharpProject> {
  let cached: Promise<CsharpProject> | undefined;
  return () => cached ??= loadUncached(target);
}
