import { mkdtemp, mkdir, realpath, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

import { resolveCsharpProject } from "./project.js";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

async function temporaryRoot(): Promise<string> {
  const root = await mkdtemp(join(await realpath(tmpdir()), "codeinspectus-csharp-project-"));
  roots.push(root);
  return root;
}

describe("C# project loader", () => {
  it("loads production C# while excluding tests, generated files, and build trees", async () => {
    const root = await temporaryRoot();
    await mkdir(join(root, "src"), { recursive: true });
    await mkdir(join(root, "tests"), { recursive: true });
    await mkdir(join(root, "obj"), { recursive: true });
    await writeFile(join(root, "src", "Agent.cs"), "class Agent {}\n");
    await writeFile(join(root, "src", "AgentTest.cs"), "class AgentTest {}\n");
    await writeFile(join(root, "tests", "Fixture.cs"), "class Fixture {}\n");
    await writeFile(join(root, "obj", "Agent.g.cs"), "// <auto-generated/>\nclass Agent {}\n");

    const project = await resolveCsharpProject(root);
    expect(project.files.map((file) => file.path)).toEqual(["src/Agent.cs"]);
  });

  it("does not follow direct file or directory-entry symbolic links", async () => {
    const root = await temporaryRoot();
    const outside = join(root, "Outside.cs");
    await writeFile(outside, "class Outside {}\n");
    await mkdir(join(root, "project"));
    await symlink(outside, join(root, "project", "Linked.cs"));

    const directory = await resolveCsharpProject(join(root, "project"));
    expect(directory.files).toEqual([]);
    expect(directory.limitations?.join(" ")).toContain("symbolic-link C# source entry Linked.cs");

    const direct = await resolveCsharpProject(join(root, "project", "Linked.cs"));
    expect(direct.files).toEqual([]);
    expect(direct.limitations?.join(" ")).toContain("symbolic-link C# source target");
  });
});
